In [1]:

import numpy as np
array=np.random.random(size=(10,1))
print(array)
mean=array.mean()
print(mean)

[[0.42545708]
 [0.17285397]
 [0.45249721]
 [0.4114412 ]
 [0.93547278]
 [0.29765688]
 [0.45904925]
 [0.41597022]
 [0.260514  ]
 [0.91075066]]
0.47416632666987396


In [2]:
array1=np.random.random(size=(20,1))
print(array1)
var=array1.var()
std=array1.std()
print(var)
print(std)

[[0.79790868]
 [0.99832639]
 [0.80696932]
 [0.35815702]
 [0.64539303]
 [0.60752018]
 [0.41873768]
 [0.56230478]
 [0.77507964]
 [0.90742769]
 [0.5812165 ]
 [0.16724572]
 [0.05673204]
 [0.77888146]
 [0.78984047]
 [0.5598278 ]
 [0.95717369]
 [0.70974328]
 [0.49105584]
 [0.39505668]]
0.05999881910469005
0.2449465637739996


In [3]:
arr=np.random.random(size=(10,20))
arr1=np.random.random(size=(20,25))
arr2=np.matmul(arr,arr1)
print(arr2)
arr2.sum()

[[4.98922644 6.12458472 5.23176983 3.87793728 6.73275945 6.53906077
  5.88315955 5.52416075 6.7233757  7.0328642  4.89398349 4.6557228
  6.66457879 5.46143953 5.70983296 5.78976696 6.45848487 6.05479804
  6.12710416 5.92812019 4.7076215  5.89308523 6.26735762 6.65976659
  6.50518188]
 [4.36593658 6.29154603 4.8482065  3.58715327 6.91192679 6.31311967
  4.69882085 4.92418436 6.60334318 6.34608927 5.08312269 4.86756927
  5.06119628 4.93377895 5.68232629 6.00442916 6.37905235 4.85134581
  6.23087569 4.82895529 4.69632969 5.97043963 5.89473869 5.5319206
  5.98973397]
 [4.39134043 5.66271323 4.162215   3.18244813 6.56087176 5.67711489
  4.59368645 4.68386801 5.72118523 6.22055577 4.62911844 3.9777803
  5.37695167 5.43435734 4.90989286 4.98564755 6.46533941 5.36103405
  5.47860903 4.799356   4.7398671  5.43178232 5.57530288 5.2582945
  5.47412867]
 [4.38324469 5.81650339 4.72460006 3.42456628 6.29607103 5.37051509
  4.41177173 4.51192452 5.65751914 6.25553632 4.05967655 3.84435215
  6.023113

1322.9729032620385

In [4]:
array2=np.random.random(size=(10,1))
print(array2)
print("*"*80)
array3=np.ndarray((10,1))
def func(x):
    return 1/1+ np.exp(-x)
List=list()
List1=list()
for i in range(0,array2.shape[0]):
    List.clear()
    for j in array2[i]:
        List.append(func(j))
    List1.append(List)
print(List1)
np.array(List1)

[[0.60500387]
 [0.42997019]
 [0.84252356]
 [0.07984454]
 [0.81408051]
 [0.3381457 ]
 [0.56059549]
 [0.12717488]
 [0.52410914]
 [0.20868037]]
********************************************************************************
[[1.8116546214714122], [1.8116546214714122], [1.8116546214714122], [1.8116546214714122], [1.8116546214714122], [1.8116546214714122], [1.8116546214714122], [1.8116546214714122], [1.8116546214714122], [1.8116546214714122]]


array([[1.81165462],
       [1.81165462],
       [1.81165462],
       [1.81165462],
       [1.81165462],
       [1.81165462],
       [1.81165462],
       [1.81165462],
       [1.81165462],
       [1.81165462]])